"""
Iteration 43 - Revenue Export (CSV/PDF) and Auto-Notification Tests
Tests:
1. CSV export with Kalmori Distribution branding
2. PDF export returns valid PDF
3. Export endpoints require authentication
4. Admin royalty import creates in-app notifications
5. Notification message includes earnings amount and Kalmori Distribution
"""

import pytest
import requests
import os
import io

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

class TestRevenueExportCSV:
    """CSV Export endpoint tests"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Login and get auth cookie"""
        self.session = requests.Session()
        login_resp = self.session.post(f"{BASE_URL}/api/auth/login", json={
            "email": "admin@tunedrop.com",
            "password": "Admin123!"
        })
        assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
        self.user = login_resp.json()
        yield
        self.session.close()
    
    def test_csv_export_returns_200(self):
        """CSV export endpoint returns 200"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200, f"CSV export failed: {resp.status_code}"
        print("PASS: CSV export returns 200")
    
    def test_csv_export_content_type(self):
        """CSV export returns text/csv content type"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content_type = resp.headers.get('Content-Type', '')
        assert 'text/csv' in content_type, f"Expected text/csv, got {content_type}"
        print("PASS: CSV export has correct content-type")
    
    def test_csv_export_has_kalmori_branding(self):
        """CSV export contains Kalmori Distribution branding in header"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "Kalmori Distribution" in content, "CSV missing Kalmori Distribution branding"
        assert "Personal Earnings Report" in content, "CSV missing Personal Earnings Report header"
        print("PASS: CSV has Kalmori Distribution branding")
    
    def test_csv_export_has_streaming_section(self):
        """CSV export contains streaming earnings section"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "STREAMING EARNINGS" in content, "CSV missing STREAMING EARNINGS section"
        assert "Platform" in content, "CSV missing Platform column"
        assert "Streams" in content, "CSV missing Streams column"
        print("PASS: CSV has streaming earnings section")
    
    def test_csv_export_has_kalmori_section(self):
        """CSV export contains Kalmori Distribution earnings section"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        # Check for Kalmori section (may or may not exist depending on data)
        if "KALMORI DISTRIBUTION EARNINGS" in content:
            print("PASS: CSV has Kalmori Distribution earnings section")
        else:
            print("INFO: No Kalmori Distribution earnings section (user may not have imported royalties)")
    
    def test_csv_export_has_artist_name(self):
        """CSV export contains artist name"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "Artist:" in content, "CSV missing Artist field"
        print("PASS: CSV has artist name")
    
    def test_csv_export_has_plan_info(self):
        """CSV export contains plan information"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "Plan:" in content, "CSV missing Plan field"
        print("PASS: CSV has plan information")
    
    def test_csv_export_has_generated_date(self):
        """CSV export contains generated date"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "Generated:" in content, "CSV missing Generated date"
        print("PASS: CSV has generated date")
    
    def test_csv_export_has_footer(self):
        """CSV export contains Kalmori footer"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 200
        content = resp.text
        assert "This report was generated by Kalmori Distribution" in content, "CSV missing footer"
        print("PASS: CSV has Kalmori footer")


class TestRevenueExportPDF:
    """PDF Export endpoint tests"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Login and get auth cookie"""
        self.session = requests.Session()
        login_resp = self.session.post(f"{BASE_URL}/api/auth/login", json={
            "email": "admin@tunedrop.com",
            "password": "Admin123!"
        })
        assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
        self.user = login_resp.json()
        yield
        self.session.close()
    
    def test_pdf_export_returns_200(self):
        """PDF export endpoint returns 200"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/pdf")
        assert resp.status_code == 200, f"PDF export failed: {resp.status_code}"
        print("PASS: PDF export returns 200")
    
    def test_pdf_export_content_type(self):
        """PDF export returns application/pdf content type"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/pdf")
        assert resp.status_code == 200
        content_type = resp.headers.get('Content-Type', '')
        assert 'application/pdf' in content_type, f"Expected application/pdf, got {content_type}"
        print("PASS: PDF export has correct content-type")
    
    def test_pdf_export_is_valid_pdf(self):
        """PDF export returns valid PDF file (starts with %PDF)"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/pdf")
        assert resp.status_code == 200
        content = resp.content
        assert content[:4] == b'%PDF', "PDF does not start with %PDF magic bytes"
        print("PASS: PDF export is valid PDF file")
    
    def test_pdf_export_has_content_disposition(self):
        """PDF export has Content-Disposition header for download"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue/export/pdf")
        assert resp.status_code == 200
        content_disp = resp.headers.get('Content-Disposition', '')
        assert 'attachment' in content_disp or 'filename' in content_disp, f"Missing Content-Disposition: {content_disp}"
        print("PASS: PDF export has Content-Disposition header")


class TestExportAuthentication:
    """Export endpoints require authentication"""
    
    def test_csv_export_requires_auth(self):
        """CSV export returns 401 without authentication"""
        session = requests.Session()
        resp = session.get(f"{BASE_URL}/api/analytics/revenue/export/csv")
        assert resp.status_code == 401, f"Expected 401, got {resp.status_code}"
        print("PASS: CSV export requires authentication (401 without auth)")
    
    def test_pdf_export_requires_auth(self):
        """PDF export returns 401 without authentication"""
        session = requests.Session()
        resp = session.get(f"{BASE_URL}/api/analytics/revenue/export/pdf")
        assert resp.status_code == 401, f"Expected 401, got {resp.status_code}"
        print("PASS: PDF export requires authentication (401 without auth)")


class TestRoyaltyImportNotifications:
    """Admin royalty import creates notifications for matched users"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Login as admin"""
        self.session = requests.Session()
        login_resp = self.session.post(f"{BASE_URL}/api/auth/login", json={
            "email": "admin@tunedrop.com",
            "password": "Admin123!"
        })
        assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
        self.user = login_resp.json()
        yield
        self.session.close()
    
    def test_notifications_endpoint_exists(self):
        """Notifications endpoint returns 200"""
        resp = self.session.get(f"{BASE_URL}/api/notifications")
        assert resp.status_code == 200, f"Notifications endpoint failed: {resp.status_code}"
        print("PASS: Notifications endpoint returns 200")
    
    def test_royalty_update_notification_exists(self):
        """Check if royalty_update notification exists from previous import"""
        resp = self.session.get(f"{BASE_URL}/api/notifications")
        assert resp.status_code == 200
        notifications = resp.json()
        
        # Look for royalty_update type notifications
        royalty_notifications = [n for n in notifications if n.get('type') == 'royalty_update']
        
        if royalty_notifications:
            print(f"PASS: Found {len(royalty_notifications)} royalty_update notification(s)")
            # Check notification content
            latest = royalty_notifications[0]
            assert 'message' in latest, "Notification missing message"
            assert 'Kalmori Distribution' in latest['message'], "Notification missing Kalmori Distribution mention"
            assert '$' in latest['message'], "Notification missing earnings amount"
            print(f"PASS: Notification message: {latest['message']}")
        else:
            print("INFO: No royalty_update notifications found - may need to import royalties first")
    
    def test_notification_has_required_fields(self):
        """Notifications have required fields"""
        resp = self.session.get(f"{BASE_URL}/api/notifications")
        assert resp.status_code == 200
        notifications = resp.json()
        
        if notifications:
            notif = notifications[0]
            assert 'id' in notif, "Notification missing id"
            assert 'type' in notif, "Notification missing type"
            assert 'message' in notif, "Notification missing message"
            assert 'read' in notif, "Notification missing read status"
            assert 'created_at' in notif, "Notification missing created_at"
            print("PASS: Notifications have required fields")
        else:
            print("INFO: No notifications to verify fields")


class TestRevenueAnalyticsEndpoint:
    """Verify Revenue Analytics endpoint still works (regression)"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Login and get auth cookie"""
        self.session = requests.Session()
        login_resp = self.session.post(f"{BASE_URL}/api/auth/login", json={
            "email": "admin@tunedrop.com",
            "password": "Admin123!"
        })
        assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
        yield
        self.session.close()
    
    def test_revenue_analytics_returns_200(self):
        """Revenue analytics endpoint returns 200"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue")
        assert resp.status_code == 200, f"Revenue analytics failed: {resp.status_code}"
        print("PASS: Revenue analytics returns 200")
    
    def test_revenue_analytics_has_summary(self):
        """Revenue analytics has summary section"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue")
        assert resp.status_code == 200
        data = resp.json()
        assert 'summary' in data, "Missing summary section"
        print("PASS: Revenue analytics has summary section")
    
    def test_revenue_analytics_has_kalmori(self):
        """Revenue analytics has kalmori section"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue")
        assert resp.status_code == 200
        data = resp.json()
        assert 'kalmori' in data, "Missing kalmori section"
        print("PASS: Revenue analytics has kalmori section")
    
    def test_revenue_analytics_has_combined(self):
        """Revenue analytics has combined section"""
        resp = self.session.get(f"{BASE_URL}/api/analytics/revenue")
        assert resp.status_code == 200
        data = resp.json()
        assert 'combined' in data, "Missing combined section"
        print("PASS: Revenue analytics has combined section")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
